import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./componentes/navbar";
import Navbar1 from "./componentes/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "PaginaWeb",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <Navbar1 />
        {children}
      </body>
    </html>
  );
}
